import Block from "./Block";
import Badge from "./Badge";
import Button from "./Button";
import Card from "./Card";
import Input from "./Input";
import Text from "./Text";
import Progress from "./Progress";
import Divider from "./Divider";
import Switch from "./Switch";
import SelectDistric from "./SelectDistric";
export { Block, Badge, Button, Card, Input, Text,SelectDistric, Progress, Divider, Switch };